credentials:
  usernames:
    hr_user:
      name: HR Team Leader
      password: "$2b$12$Xo.vY5xXvU97ChJ3StMLpe.6xUvqaJkQRujNVX7nUzzEumk3Y/d12"  # hashed for 'hr123'
      role: HR
    admin_user:
      name: Admin Manager
      password: "$2b$12$ON1HWWRUI3aXbxdZyKyaMeNxfM4Bb3y4LbAbZd9G0Tk2OR3RfIjoq"  # hashed for 'admin123'
      role: Admin
cookie:
  name: resume_cookie
  key: super_secret_key
  expiry_days: 3
